# Generated by Django 4.1.6 on 2023-02-03 11:22

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('title', models.CharField(max_length=50)),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('types', models.CharField(choices=[('director', 'Director'), ('writer', 'Writer'), ('actor', 'Actor')], max_length=50)),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('poster', models.ImageField(null=True, upload_to=api.models.poster_file_path)),
                ('bg_picture', models.ImageField(null=True, upload_to=api.models.bg_picture_file_path)),
                ('release_year', models.IntegerField()),
                ('mpa_rating', models.CharField(choices=[('G', 'G'), ('PG', 'Pg'), ('PG-13', 'Pg 13'), ('R', 'R'), ('NC-17', 'Nc 17')], max_length=50)),
                ('imdb_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('duration', models.IntegerField()),
                ('directors', models.ManyToManyField(related_name='movies_as_director', to='api.person')),
                ('genres', models.ManyToManyField(related_name='movies', to='api.genre')),
                ('stars', models.ManyToManyField(related_name='movies_as_star', to='api.person')),
                ('writers', models.ManyToManyField(related_name='movies_as_writer', to='api.person')),
            ],
            bases=('api.basemodel',),
        ),
    ]
