# Generated by Django 4.1.6 on 2023-02-03 08:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('types', models.CharField(choices=[(api.models.Person.PersonStatus['DIRECTOR'], 'director'), (api.models.Person.PersonStatus['WRITER'], 'writer'), (api.models.Person.PersonStatus['ACTOR'], 'actor')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('poster', models.ImageField(null=True, upload_to=api.models.poster_file_path)),
                ('bg_picture', models.ImageField(null=True, upload_to=api.models.bg_picture_file_path)),
                ('release_year', models.IntegerField()),
                ('mpa_rating', models.CharField(choices=[(api.models.Movie.MPARating['G'], 'G'), (api.models.Movie.MPARating['PG'], 'PG'), (api.models.Movie.MPARating['PG_13'], 'PG-13'), (api.models.Movie.MPARating['R'], 'R'), (api.models.Movie.MPARating['NC_17'], 'NC-17')], max_length=50)),
                ('imdb_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('duration', models.IntegerField()),
                ('directors', models.ManyToManyField(related_name='movies_as_director', to='api.person')),
                ('genres', models.ManyToManyField(related_name='movies', to='api.genre')),
                ('stars', models.ManyToManyField(related_name='movies_as_star', to='api.person')),
                ('writers', models.ManyToManyField(related_name='movies_as_writer', to='api.person')),
            ],
        ),
    ]
