# Generated by Django 4.1.6 on 2023-02-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='types',
            field=models.CharField(choices=[('director', 'DIRECTOR'), ('writer', 'WRITER'), ('actor', 'ACTOR')], max_length=50),
        ),
    ]
