# Generated by Django 4.1.6 on 2023-02-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_person_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='types',
            field=models.CharField(choices=[('DIRECTOR', 'director'), ('WRITER', 'writer'), ('ACTOR', 'actor')], max_length=50),
        ),
    ]
