# Generated by Django 4.1.6 on 2023-02-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_person_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mpa_rating',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'Pg'), ('PG-13', 'Pg 13'), ('R', 'R'), ('NC-17', 'Nc 17')], max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='types',
            field=models.CharField(choices=[('director', 'Director'), ('writer', 'Writer'), ('actor', 'Actor')], max_length=50),
        ),
    ]
